### ISSUE TITLE
Way to do this for The Full Package?

### ISSUE THREAD

**Issue by KowabungaOfficial** [RoseTheFlower/SaintsRowTTRNoLetterbox#1]
The full package has SaintsRowTheThird_DX11.exe and a SaintsRowTheThird.exe, both launch the game, one in dx9 and the other dx11. Wondering if this could be updated to fix the issue in The Full Packaged version.

**Comment by RoseTheFlower** [comment]
I'm not sure I understand the question. On Epic, I see just one executable after installing Saints Row The Third Remastered.

For the original game, according to the WSGF report, the cutscenes are FMVs but I'm not sure.

**Comment by KowabungaOfficial** [comment]
> I'm not sure I understand the question. On Epic, I see just one executable after installing Saints Row The Third Remastered.
> 
> For the original game, according to the WSGF report, the cutscenes are FMVs but I'm not sure.

In "The Full Package" the cutscenes are all in game. Basically wanted to see if removing letterbox was possible for the og with all the dlc "aka Saints Row The Third The Full Package". Non-remastered game essentially. As far as I remember all cutscenes from all games have been done in game because of the boss (main creatable character), unless I'm mistaken.

**Comment by RoseTheFlower** [comment]
Try [this](https://mega.nz/file/4ddDEAIY#3RDtXPCPRnkmh1u4cOjRus3iQ42w8_4TWrNkRQbykDI) and then I'll think of whether to make it more public. It should be extracted into the game folder.

**Comment by KowabungaOfficial** [comment]
> Try [this](https://mega.nz/file/4ddDEAIY#3RDtXPCPRnkmh1u4cOjRus3iQ42w8_4TWrNkRQbykDI) and then I'll think of whether to make it more public. It should be extracted into the game folder.

Thanks I'll test it in the morning. Thanks so much.

**Comment by RoseTheFlower** [comment]
I removed the old file at the link and [created](https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/saintsrowtt) a potentially more reliable solution based on the game code. Compatible with DX10/11 only though.

**Comment by KowabungaOfficial** [comment]
> I removed the old file at the link and [created](https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/saintsrowtt) a potentially more reliable solution based on the game code. Compatible with DX10/11 only though.

You are the best, thank you. Went ahead and donated (ko-fi: 10$) to you for the help. Much appreciated, and many thanks.
